Repository kyma-project/compass-manager, pull requests merged in 2023-04, with the labels that each got.

#2 Scaffolding for the Compass-manager
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  PROJECT
  api/.gitkeep
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  controllers/.gitkeep
  go.mod
  go.sum
  hack/boilerplate.go.txt
  main.go
Labels: area/application-connector, size/XXL, lgtm

#3 Configure security scans
  .trivy.yaml
Labels: lgtm, size/S

#4 Configuration for golangci linter
  .golangci.yaml
  Makefile
Labels: size/L, lgtm
