Repository kyma-project/compass-manager, pull requests merged in 2023-12, with the labels that each got.

#57 Update dependencies for first release of the Compass Manager
  .github/workflows/golangci-lint.yaml
  controllers/compassmanager_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: size/XXL, lgtm, cla: yes

#58 Security image bump
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#56 Add link checker to compass manager
  .github/workflows/daily-markdown-link-check.yaml
  .github/workflows/pr-markdown-link-check.yaml
  mlc.config.json
Labels: size/M, lgtm, cla: yes

#46 Add a finaliser
  config/rbac/role.yaml
  controllers/compassmanager_controller.go
  controllers/compassmanager_controller_test.go
  controllers/status.go
  controllers/status_test.go
  controllers/suite_test.go
  main.go
Labels: size/XL, lgtm, cla: yes

#59 Replace default kubebuilder identifiers in helm charts with specific for compass-manager
  config/default/kustomization.yaml
  config/default/manager_config_patch.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
Labels: size/M, lgtm, cla: yes

#61 Change App Conn module name
  controllers/compassmanager_controller.go
Labels: size/XS, lgtm, cla: yes

#60 removes a blog deadlink from 3rd party client
  third_party/machinebox/graphql/README.md
Labels: size/XS, area/documentation, lgtm, cla: yes

#62 Fix link to Code of Conduct
  CODE_OF_CONDUCT.md
Labels: size/XS, lgtm, cla: yes

#63 Change the way of watching App Conn module
  controllers/compassmanager_controller.go
  controllers/compassmanager_controller_test.go
Labels: area/application-connector, lgtm, size/S, cla: yes

#64 Update kustomize templates to fix and align with helm kcp charts
  Makefile
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_compassmanagermappings.yaml
  config/crd/patches/webhook_in_compassmanagermappings.yaml
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
Labels: size/M, lgtm, cla: yes

#68 Create dependabot.yml
  .github/dependabot.yml
Labels: lgtm, size/S, cla: yes

#66 Controller triggers only when App Conn module in `status` was updated
  controllers/compassmanager_controller.go
  go.mod
Labels: area/application-connector, size/M, lgtm, cla: yes

#73 configures golang/govulncheck-action
  .github/workflows/golangci-lint.yaml
  .github/workflows/run-vuln-check.yaml
  Dockerfile
Labels: lgtm, size/S, cla: yes

#74 switches linter go version from 1.21.5 to 1.21
  .github/workflows/golangci-lint.yaml
Labels: size/XS, lgtm, cla: yes

#75 Bumps k8s.io components and matryer/is
  go.mod
  go.sum
Labels: size/M, lgtm, cla: yes

#67 Add metrics
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manager/metrics.yaml
  config/prometheus/monitor.yaml
  controllers/compassmanager_controller.go
  controllers/metrics/metrics.go
  controllers/suite_test.go
  go.mod
  internal/director/mocks/Client.go
  internal/graphql/mocks/Client.go
  internal/oauth/mocks/Client.go
  main.go
Labels: size/L, lgtm, cla: yes

#78 Fix go.mod
  go.mod
  go.sum
Labels: size/M, lgtm, cla: yes

#79 Bump image in security scans
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#82 Add URL to Compass Director as env parameter
  config/manager/manager.yaml
  main.go
Labels: size/XS, lgtm, cla: yes

#85 Enable runtime registration in compass-manager configuration
  config/manager/manager.yaml
Labels: size/XS, lgtm, cla: yes
