Repository kyma-project/compass-manager, pull requests merged in 2023-11, with the labels that each got.

#39 Add statuses
  api/v1beta1/compassmanagermapping_types.go
  config/crd/bases/operator.kyma-project.io_compassmanagermappings.yaml
  config/rbac/role.yaml
  controllers/compassmanager_controller.go
  controllers/compassmanager_controller_test.go
  controllers/mocks/Configurator.go
  controllers/mocks/Registrator.go
  controllers/registrator.go
  controllers/suite_test.go
  go.mod
  go.sum
  internal/apperrors/apperrors.go
  internal/director/directorclient.go
  internal/director/mocks/Client.go
  internal/graphql/mocks/Client.go
  internal/oauth/mocks/Client.go
  main.go
Labels: size/XL, lgtm

#45 Add finalizer
  api/v1beta1/compassmanagermapping_types.go
  config/crd/bases/operator.kyma-project.io_compassmanagermappings.yaml
  config/rbac/role.yaml
  controllers/compassmanager_controller.go
  controllers/compassmanager_controller_test.go
  controllers/mocks/Configurator.go
  controllers/mocks/Registrator.go
  controllers/registrator.go
  controllers/suite_test.go
  go.mod
  go.sum
  internal/apperrors/apperrors.go
  internal/director/directorclient.go
  internal/director/mocks/Client.go
  internal/graphql/mocks/Client.go
  internal/oauth/mocks/Client.go
  main.go
Labels: size/XL, do-not-merge/work-in-progress

#47 Bump sec image, change feature flag to false
  config/manager/manager.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#48 Fix security in Compass Manager
  Dockerfile
  go.mod
  go.sum
Labels: area/application-connector, size/XS, lgtm

#55 Delete `kube-rbac-proxy` sidecar from Compass Manager deployment
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
Labels: size/L, lgtm, cla: yes
