Repository kyma-project/compass-manager, pull requests merged in 2024-03, with the labels that each got.

#125 Add testing strategy for Compass Manager
  docs/contributor/testing-strategy.md
Labels: size/L, area/documentation, lgtm, cla: yes

#123 Rename the GitHub Actions
  .github/workflows/golangci-lint.yaml
  .github/workflows/pr-markdown-link-check.yaml
  .github/workflows/run-vuln-check.yaml
  .github/workflows/tests.yml
  .github/workflows/trivy.yml
  controllers/configurator.go
Labels: lgtm, size/S, cla: yes

#142 Compass-Manager: Increase reconciliation requeue time when kubeconfig is missing
  .github/workflows/run-vuln-check.yaml
  Dockerfile
  controllers/compassmanager_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: size/L, lgtm, cla: yes
