Repository kyma-project/compass-manager, pull requests merged in 2024-09, with the labels that each got.

#206 docs: Add mandatory sections to README.md
  README.md
Labels: lgtm, size/S, cla: yes

#207 Fix workflow
  .github/workflows/compass-manager.yaml
Labels: size/L, lgtm, cla: yes

#208 Pipelines/fix/checkouts+summary
  .github/workflows/compass-manager.yaml
Labels: size/M, lgtm, cla: yes

#210 Remove extra bracket in pipelines
  .github/workflows/compass-manager.yaml
Labels: size/XS, lgtm, cla: yes

#212 Add missing nl
  .github/workflows/compass-manager.yaml
Labels: size/XS, lgtm, cla: yes

#213 Add more newlines to summary
  .github/workflows/compass-manager.yaml
Labels: size/XS, lgtm, cla: yes

#211 Bump dependencies (fixes trivy)
  go.mod
  go.sum
Labels: size/S, cla: yes

#216 Update Golang version to 1.23.1
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  Dockerfile
  go.mod
  go.sum
  main.go
Labels: size/L, lgtm, cla: yes
