Repository kyma-project/compass-manager, pull requests merged in 2024-12, with the labels that each got.

#234 Stop processing of already registered Kyma Runtimes with annotation compass-runtime-id-for-migration
  controllers/compassmanager_controller.go
  controllers/compassmanager_controller_test.go
Labels: size/M, lgtm, cla: yes

#237 replaces golang.org/x/crypto to v0.31.0
  go.mod
  go.sum
Labels: lgtm, size/S, cla: yes

#238 replaces golang.org/x/net to v0.33.0
  go.mod
  go.sum
Labels: size/XS, lgtm, cla: yes

#236 Validation of the 3rd party payload
  config/manager/manager.yaml
  controllers/configurator.go
  controllers/configurator_test.go
  internal/apperrors/apperrors.go
  internal/director/directorclient.go
  internal/director/directorclient_test.go
  main.go
Labels: size/L, lgtm, cla: yes
