Repository kyma-project/compass-manager, pull requests merged in 2024-01, with the labels that each got.

#81 Improve metrics
  controllers/compassmanager_controller.go
  controllers/metrics/metrics.go
  controllers/status/status.go
  controllers/status/status_test.go
  go.sum
Labels: size/L, lgtm, cla: yes

#88 Fix metric `"Ready"` bug
  controllers/compassmanager_controller.go
Labels: size/XS, lgtm, cla: yes

#95 Dry run flag
  controllers/compassmanager_controller.go
  controllers/dryrun.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: size/M, lgtm, cla: yes

#98 Bump security image
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#92 [Compass Manager] The new URL to Compass System on DEV
  config/manager/manager.yaml
  main.go
Labels: size/XS, lgtm, cla: yes

#99 Document dry run flag
  README.md
  controllers/compassmanager_controller.go
  main.go
Labels: lgtm, size/S, cla: yes

#105 Fix dry-run label
  controllers/compassmanager_controller.go
Labels: size/XS, lgtm, cla: yes
