Repository kyma-project/compass-manager, pull requests merged in 2024-02, with the labels that each got.

#108 Improve README
  README.md
  go.mod
  go.sum
Labels: size/L, lgtm, cla: yes

#115 Trigger trivy to fail
  .github/workflows/trivy.yml
Labels: size/XS, lgtm, cla: yes

#116 Trivy scanning in GitHub Action
  .github/workflows/trivy.yml
  .trivy.yaml
Labels: size/M, lgtm, cla: yes

#117 Create Compass Manager tests in GH Actions
  .github/workflows/tests.yml
  controllers/configurator.go
Labels: size/M, lgtm, cla: yes

#118 adds security policy
  SECURITY.md
Labels: size/XS, lgtm, cla: yes

#124 upgrades golangci-lint to v4 in CM
  .github/workflows/golangci-lint.yaml
Labels: size/XS, lgtm, cla: yes
